"use client"
import { useEffect } from 'react'
import './globals.css'
import { Inter } from 'next/font/google'
import { request } from '@/lib'
import Provider from '@/app/__components/Provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children,}: {children: React.ReactNode}) {
  
  useEffect(() => {
    // CSRF token request
    request().then((res) => {
      localStorage.setItem("_csrf", res.data._csrf);
    });
  })

  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <Provider>
        <body className={inter.className}>{children}</body>
      </Provider>
    </html>
  )
}
